language: rust
env:
  - RUSTFLAGS="-D warnings"
before_script:
  rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo test --all --verbose
rust
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
